name: SonarQube Simple

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Install SonarScanner
      run: dotnet tool install --global dotnet-sonarscanner

    - name: Build and analyze
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        dotnet sonarscanner begin /k:"MateusLeonardo_Candidatus" /o:"mateusleonardo" /d:sonar.token="$SONAR_TOKEN"
        
        # Build recursivo - funciona mesmo com arquivo solution com nome/extensão diferente
        dotnet build -c Release
        
        # Teste recursivo
        dotnet test -c Release --collect:"XPlat Code Coverage" --results-directory TestResults
        
        dotnet sonarscanner end /d:sonar.token="$SONAR_TOKEN"